language: go
go:
  - 1.7.x
  - 1.8.x
env:
  - GOARCH=amd64
  - GOARCH=386
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
install:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo apt-get install libsnappy1 libsnappy-dev
script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
  - chmod +x gpm
  - go get github.com/absolute8511/c-rocksdb
  - go get github.com/absolute8511/gorocksdb
  - go get github.com/cockroachdb/c-lz4
  - ./gpm install
  - ./test.sh
notifications:
  email: false
