language: go
go:
  - 1.7.x
  - 1.8.x
env:
  - GOARCH=amd64 TEST_RACE=false
  - GOARCH=amd64 TEST_RACE=true
  - GOARCH=386 TEST_RACE=false
  - GOARCH=386 TEST_RACE=true
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
install:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo apt-get install libsnappy1 libsnappy-dev
  - git clone https://github.com/absolute8511/rocksdb.git /tmp/rocksdb
  - pushd /tmp/rocksdb && USE_SSE=1 make static_lib && popd
script:
  - CGO_CFLAGS="-I/tmp/rocksdb/include" CGO_LDFLAGS="-L/tmp/rocksdb -lrocksdb -lstdc++ -lm -lsnappy -lrt" go get github.com/absolute8511/gorocksdb 
  - CGO_CFLAGS="-I/tmp/rocksdb/include" CGO_LDFLAGS="-L/tmp/rocksdb -lrocksdb -lstdc++ -lm -lsnappy -lrt" go install -race github.com/absolute8511/gorocksdb 
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install || true
  - ./test.sh
notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
